# Generated by Django 4.2.7 on 2023-11-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensueño', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id_galeria', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='')),
                ('tipo', models.CharField(choices=[('ambiente', 'Ambiente'), ('menu', 'Menu')], default='ambiente', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Galería de Imágenes',
            },
        ),
    ]
