# Generated by Django 3.2 on 2023-11-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades_de_usuario', '0003_alter_usuario_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
