# Generated by Django 4.2.7 on 2023-11-21 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ensueño', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id_testimonio', models.AutoField(primary_key=True, serialize=False)),
                ('testimonio', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateTimeField(verbose_name='Fecha de Publicación')),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades_de_usuario.usuario')),
            ],
            options={
                'verbose_name_plural': 'Testimonios',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('num_personas', models.IntegerField()),
                ('fecha_evento', models.DateTimeField(verbose_name='Fecha del evento')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensueño.ambiente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensueño.evento')),
                ('nom_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades_de_usuario.usuario')),
            ],
            options={
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_pago', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('fecha_y_hora', models.DateTimeField()),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('metodo_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensueño.metodopago')),
                ('nombre_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades_de_usuario.usuario')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id_favorito', models.AutoField(primary_key=True, serialize=False)),
                ('favorito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensueño.menu')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades_de_usuario.usuario')),
            ],
            options={
                'verbose_name_plural': 'Favoritos',
            },
        ),
    ]
