# Generated by Django 3.2 on 2023-11-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades_de_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.UUIDField(default='550e8400-e29b-41d4-a716-446655440000', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
