# Generated by Django 4.2.7 on 2023-11-21 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('img', models.ImageField(upload_to='')),
                ('id_ambiente', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ambiente', models.CharField(max_length=60)),
                ('total_mesas', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Ambientes',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('img', models.ImageField(upload_to='')),
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id_semana', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Dias',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('img', models.ImageField(upload_to='')),
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensueño.categoria')),
            ],
            options={
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodoPago', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Métodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='MenuDiario',
            fields=[
                ('id_menuDiario', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensueño.dia')),
                ('menu', models.ForeignKey(limit_choices_to={'estado': True}, on_delete=django.db.models.deletion.CASCADE, related_name='menus_diarios', to='ensueño.menu')),
            ],
            options={
                'verbose_name_plural': 'Menus Diarios',
            },
        ),
        migrations.CreateModel(
            name='MenuCarta',
            fields=[
                ('id_menuCarta', models.AutoField(primary_key=True, serialize=False)),
                ('menu', models.ForeignKey(limit_choices_to={'estado': True}, on_delete=django.db.models.deletion.CASCADE, related_name='menus_carta', to='ensueño.menu')),
            ],
            options={
                'verbose_name_plural': 'Menus a la Carta',
            },
        ),
    ]
