# Generated by Django 4.2.7 on 2023-11-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensueño', '0002_galeria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menudiario',
            name='dia',
        ),
        migrations.AddField(
            model_name='menudiario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
