# Generated by Django 4.2.7 on 2023-11-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensueño', '0003_remove_menudiario_dia_menudiario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucarta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
