# Generated by Django 3.2 on 2023-11-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensueño', '0004_menucarta_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dia',
        ),
    ]
